from alembic import op

revision = "001"
down_revision = None
branch_labels = None
depends_on = None

SCHEMA_SQL = """
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET timezone = 'America/Fortaleza';
DO $$ BEGIN EXECUTE format('ALTER DATABASE %%I SET timezone TO %%L', current_database(), 'America/Fortaleza'); END $$;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recordtype') THEN CREATE TYPE recordtype AS ENUM ('ENTRY', 'EXIT'); END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adjustmenttype') THEN CREATE TYPE adjustmenttype AS ENUM ('FORGOT_PUNCH', 'PUNCH_NOT_COUNTED', 'DELETE_PUNCH', 'WAIVER', 'EXTRA_TIME', 'DAILY_EXCESS', 'OTHER'); END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adjustmentstatus') THEN CREATE TYPE adjustmentstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED'); END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'devicekeytype') THEN CREATE TYPE devicekeytype AS ENUM ('DEVICE', 'CONSUMER'); END IF;
END $$;

CREATE TABLE companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, cnpj TEXT NOT NULL,
    address TEXT NOT NULL, phone TEXT, logo_path TEXT, auto_print_receipt BOOLEAN NOT NULL DEFAULT FALSE,
    default_printer_id INTEGER
);
CREATE TABLE printers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, address TEXT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE, paper_width INTEGER NOT NULL DEFAULT 80, company_id INTEGER NOT NULL,
    CONSTRAINT fk_printers_company_id FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
);
ALTER TABLE companies ADD CONSTRAINT fk_companies_default_printer_id
    FOREIGN KEY (default_printer_id) REFERENCES printers (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL, name TEXT, email TEXT,
    cpf TEXT, pis TEXT, endereco TEXT, data_nascimento DATE, password_hash TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    role TEXT NOT NULL DEFAULT 'EMPLOYEE' CHECK (role IN ('EMPLOYEE', 'MANAGER', 'MAINTAINER')),
    can_manual_punch_desktop BOOLEAN NOT NULL DEFAULT TRUE, can_manual_punch_mobile BOOLEAN NOT NULL DEFAULT FALSE,
    can_export_report BOOLEAN NOT NULL DEFAULT FALSE, is_exempt_from_rules BOOLEAN NOT NULL DEFAULT FALSE,
    is_tolerance_exempt BOOLEAN NOT NULL DEFAULT FALSE, auto_print_receipt BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE device_credentials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
    key_type devicekeytype NOT NULL DEFAULT 'DEVICE', api_key_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE firmwares (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version TEXT NOT NULL, file_path TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE holidays (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date DATE NOT NULL UNIQUE, name TEXT NOT NULL);
CREATE TABLE user_biometrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL, sensor_index INTEGER,
    template_data TEXT, finger_id INTEGER, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_biometrics_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE user_work_schedule_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), daily_hours DOUBLE PRECISION NOT NULL,
    entry_1 TIME WITHOUT TIME ZONE, exit_1 TIME WITHOUT TIME ZONE, entry_2 TIME WITHOUT TIME ZONE,
    exit_2 TIME WITHOUT TIME ZONE, valid_from DATE NOT NULL, valid_until DATE,
    is_daily_excess_enabled BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_user_work_schedule_configs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE time_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL, record_type recordtype NOT NULL,
    record_datetime TIMESTAMPTZ NOT NULL, ip_address TEXT, device_name TEXT, platform TEXT, biometric_id INTEGER,
    edited_by INTEGER, edit_justification TEXT, deleted_at TIMESTAMPTZ, deleted_by INTEGER,
    is_ignored BOOLEAN NOT NULL DEFAULT FALSE, is_verified BOOLEAN NOT NULL DEFAULT FALSE, original_record_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ,
    CONSTRAINT fk_time_records_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_time_records_biometric_id FOREIGN KEY (biometric_id) REFERENCES user_biometrics (id) ON DELETE SET NULL,
    CONSTRAINT fk_time_records_edited_by FOREIGN KEY (edited_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_time_records_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_time_records_original_record_id FOREIGN KEY (original_record_id) REFERENCES time_records (id) ON DELETE SET NULL
);
CREATE TABLE adjustment_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL,
    adjustment_type adjustmenttype NOT NULL, record_type recordtype, target_date DATE NOT NULL,
    time TIME WITHOUT TIME ZONE, amount_hours DOUBLE PRECISION, reason_text TEXT,
    status adjustmentstatus NOT NULL DEFAULT 'PENDING', manager_id INTEGER, manager_comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ, deleted_by INTEGER, approved_amount_hours DOUBLE PRECISION,
    CONSTRAINT fk_adjustment_requests_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_adjustment_requests_manager_id FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_adjustment_requests_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE TABLE adjustment_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, adjustment_request_id INTEGER NOT NULL,
    file_path TEXT NOT NULL, file_type TEXT NOT NULL, uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adjustment_attachments_request_id FOREIGN KEY (adjustment_request_id) REFERENCES adjustment_requests (id) ON DELETE CASCADE
);
CREATE TABLE payroll_closures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    year INTEGER NOT NULL CHECK (year >= 2000), is_closed BOOLEAN NOT NULL DEFAULT TRUE,
    closed_by_user_id INTEGER NOT NULL, closed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, report_path TEXT,
    deleted_at TIMESTAMPTZ, deleted_by INTEGER, reopen_observation TEXT,
    CONSTRAINT fk_payroll_closures_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payroll_closures_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE TABLE audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER, action TEXT NOT NULL, entity TEXT NOT NULL,
    entity_id INTEGER, old_data JSONB, new_data JSONB, timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE TABLE routine_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, routine_type TEXT NOT NULL,
    execution_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, target_date DATE, status TEXT NOT NULL, details TEXT
);

CREATE UNIQUE INDEX ix_companies_cnpj ON companies (cnpj);
CREATE INDEX ix_companies_id ON companies (id); CREATE INDEX ix_companies_default_printer_id ON companies (default_printer_id);
CREATE INDEX ix_printers_id ON printers (id); CREATE INDEX ix_printers_company_id ON printers (company_id);
CREATE UNIQUE INDEX ix_users_username ON users (username); CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_cpf ON users (cpf); CREATE INDEX ix_users_id ON users (id);
CREATE INDEX idx_users_active_role ON users (is_active, role); CREATE INDEX idx_users_name_trgm ON users USING gin (name gin_trgm_ops);
CREATE INDEX ix_device_credentials_id ON device_credentials (id); CREATE INDEX idx_device_credentials_lookup ON device_credentials (api_key_hash, key_type, is_active);
CREATE INDEX ix_firmwares_id ON firmwares (id); CREATE INDEX idx_firmwares_version_created ON firmwares (version, created_at DESC);
CREATE INDEX ix_holidays_id ON holidays (id); CREATE INDEX ix_user_biometrics_id ON user_biometrics (id);
CREATE INDEX ix_user_biometrics_user_id ON user_biometrics (user_id); CREATE INDEX idx_user_biometrics_sensor_lookup ON user_biometrics (sensor_index);
CREATE INDEX ix_user_work_schedule_configs_id ON user_work_schedule_configs (id); CREATE INDEX ix_user_work_schedule_configs_user_id ON user_work_schedule_configs (user_id);
CREATE INDEX idx_user_work_schedules_active ON user_work_schedule_configs (user_id, valid_from, valid_until);
CREATE INDEX ix_time_records_id ON time_records (id); CREATE INDEX idx_tr_user_date ON time_records (user_id, record_datetime);
CREATE INDEX idx_tr_ignored ON time_records (is_ignored); CREATE INDEX idx_tr_active_period ON time_records (user_id, record_datetime) WHERE is_ignored = FALSE;
CREATE INDEX ix_time_records_biometric_id ON time_records (biometric_id); CREATE INDEX ix_time_records_edited_by ON time_records (edited_by);
CREATE INDEX ix_time_records_deleted_by ON time_records (deleted_by); CREATE INDEX ix_time_records_original_record_id ON time_records (original_record_id);
CREATE INDEX ix_adjustment_requests_id ON adjustment_requests (id); CREATE INDEX idx_adj_user_date ON adjustment_requests (user_id, target_date);
CREATE INDEX idx_adj_status ON adjustment_requests (status); CREATE INDEX ix_adjustment_requests_manager_id ON adjustment_requests (manager_id);
CREATE INDEX ix_adjustment_requests_deleted_by ON adjustment_requests (deleted_by); CREATE INDEX ix_adjustment_attachments_id ON adjustment_attachments (id);
CREATE INDEX ix_adjustment_attachments_request_id ON adjustment_attachments (adjustment_request_id);
CREATE INDEX ix_payroll_closures_id ON payroll_closures (id); CREATE INDEX idx_payroll_closures_period ON payroll_closures (year, month);
CREATE INDEX ix_payroll_closures_closed_by ON payroll_closures (closed_by_user_id); CREATE INDEX ix_payroll_closures_deleted_by ON payroll_closures (deleted_by);
CREATE INDEX ix_audit_logs_id ON audit_logs (id); CREATE INDEX idx_audit_user_action ON audit_logs (user_id, action);
CREATE INDEX idx_audit_entity_time ON audit_logs (entity, entity_id, timestamp); CREATE INDEX idx_audit_logs_new_data_gin ON audit_logs USING gin (new_data);
CREATE INDEX idx_audit_logs_old_data_gin ON audit_logs USING gin (old_data); CREATE INDEX ix_routine_logs_id ON routine_logs (id);
CREATE INDEX ix_routine_logs_routine_type ON routine_logs (routine_type); CREATE INDEX idx_routine_logs_execution_time ON routine_logs (execution_time DESC);
"""


def upgrade() -> None:
    op.get_bind().exec_driver_sql(SCHEMA_SQL)


def downgrade() -> None:
    raise NotImplementedError("A migração de base não pode ser revertida automaticamente.")
