from alembic import op

revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE daily_summaries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            apuration_date DATE NOT NULL,
            worked_minutes INTEGER NOT NULL DEFAULT 0,
            accounted_minutes INTEGER NOT NULL DEFAULT 0,
            expected_minutes INTEGER NOT NULL DEFAULT 0,
            excess_minutes INTEGER NOT NULL DEFAULT 0,
            authorized_excess_minutes INTEGER NOT NULL DEFAULT 0,
            missing_minutes INTEGER NOT NULL DEFAULT 0,
            waiver_minutes INTEGER NOT NULL DEFAULT 0,
            pending_recalculation BOOLEAN NOT NULL DEFAULT FALSE,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_daily_summaries_user_date UNIQUE (user_id, apuration_date),
            CONSTRAINT ck_daily_summaries_nonnegative CHECK (
                worked_minutes >= 0 AND accounted_minutes >= 0 AND expected_minutes >= 0
                AND excess_minutes >= 0 AND authorized_excess_minutes >= 0
                AND missing_minutes >= 0 AND waiver_minutes >= 0
            ),
            CONSTRAINT ck_daily_summaries_authorized CHECK (
                authorized_excess_minutes <= excess_minutes
            ),
            CONSTRAINT ck_daily_summaries_accounted CHECK (
                accounted_minutes <= worked_minutes
            )
        )
    """)
    op.execute("""
        CREATE INDEX ix_daily_summaries_pending
        ON daily_summaries (updated_at, id)
        WHERE pending_recalculation = TRUE
    """)


def downgrade() -> None:
    op.execute("DROP TABLE daily_summaries")
