from alembic import op

revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE daily_summaries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            apuration_date DATE NOT NULL,
            worked_minutes INTEGER NOT NULL DEFAULT 0,
            accounted_minutes INTEGER NOT NULL DEFAULT 0,
            expected_minutes INTEGER NOT NULL DEFAULT 0,
            excess_minutes INTEGER NOT NULL DEFAULT 0,
            authorized_excess_minutes INTEGER NOT NULL DEFAULT 0,
            missing_minutes INTEGER NOT NULL DEFAULT 0,
            waiver_minutes INTEGER NOT NULL DEFAULT 0,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_daily_summaries_user_date UNIQUE (user_id, apuration_date),
            CONSTRAINT ck_daily_summaries_nonnegative CHECK (
                worked_minutes >= 0 AND accounted_minutes >= 0 AND expected_minutes >= 0
                AND excess_minutes >= 0 AND authorized_excess_minutes >= 0
                AND missing_minutes >= 0 AND waiver_minutes >= 0
            ),
            CONSTRAINT ck_daily_summaries_authorized CHECK (
                authorized_excess_minutes <= excess_minutes
            ),
            CONSTRAINT ck_daily_summaries_accounted CHECK (
                accounted_minutes <= worked_minutes
            )
        )
    """)
    op.execute("LOCK TABLE audit_logs IN ACCESS EXCLUSIVE MODE")
    op.execute("DELETE FROM audit_logs WHERE action = 'LOGIN'")
    op.execute("""
        WITH ranked AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS new_id
            FROM audit_logs
        )
        UPDATE audit_logs AS target
        SET id = -ranked.new_id
        FROM ranked
        WHERE target.id = ranked.id
    """)
    op.execute("UPDATE audit_logs SET id = -id")
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('audit_logs', 'id')::regclass,
            GREATEST(COALESCE((SELECT MAX(id) FROM audit_logs), 0), 1),
            EXISTS (SELECT 1 FROM audit_logs)
        )
    """)


def downgrade() -> None:
    raise NotImplementedError("A remoção das auditorias de login não pode ser revertida")
