import argparse
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import time
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

try:
    import psycopg2
except ImportError:
    psycopg2 = None

ROOT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_SQLITE_PATH = ROOT_DIR / "spe.db"
DEFAULT_DDL_PATH = ROOT_DIR / "scripts" / "spe-db.sql"
DEFAULT_DML_PATH = ROOT_DIR / "scripts" / "data_inserts_postgresql.sql"
DEFAULT_DUMP_PATH = ROOT_DIR / "spe_dump.sql"

TABLE_ORDER = [
    "alembic_version",
    "companies",
    "printers",
    "users",
    "device_credentials",
    "firmwares",
    "holidays",
    "user_biometrics",
    "user_work_schedule_configs",
    "time_records",
    "adjustment_requests",
    "adjustment_attachments",
    "payroll_closures",
    "audit_logs",
    "routine_logs",
]

BOOLEAN_COLUMNS = {
    "companies": {"auto_print_receipt"},
    "printers": {"status"},
    "users": {
        "is_active",
        "can_manual_punch_desktop",
        "can_manual_punch_mobile",
        "can_export_report",
        "is_exempt_from_rules",
        "is_tolerance_exempt",
        "auto_print_receipt",
    },
    "device_credentials": {"is_active"},
    "user_work_schedule_configs": {"is_daily_excess_enabled"},
    "time_records": {"is_ignored", "is_verified"},
    "payroll_closures": {"is_closed"},
}

JSONB_COLUMNS = {
    "audit_logs": {"old_data", "new_data"},
}

IDENTITY_TABLES = [
    "companies",
    "printers",
    "users",
    "device_credentials",
    "firmwares",
    "holidays",
    "user_biometrics",
    "user_work_schedule_configs",
    "time_records",
    "adjustment_requests",
    "adjustment_attachments",
    "payroll_closures",
    "audit_logs",
    "routine_logs",
]

DDL_SQL_CONTENT = """BEGIN;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recordtype') THEN
        CREATE TYPE recordtype AS ENUM ('ENTRY', 'EXIT');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adjustmenttype') THEN
        CREATE TYPE adjustmenttype AS ENUM (
            'FORGOT_PUNCH',
            'PUNCH_NOT_COUNTED',
            'DELETE_PUNCH',
            'WAIVER',
            'EXTRA_TIME',
            'DAILY_EXCESS',
            'OTHER'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adjustmentstatus') THEN
        CREATE TYPE adjustmentstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'devicekeytype') THEN
        CREATE TYPE devicekeytype AS ENUM ('DEVICE', 'CONSUMER');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cnpj VARCHAR(18) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    logo_path VARCHAR(500),
    auto_print_receipt BOOLEAN NOT NULL DEFAULT FALSE,
    default_printer_id INTEGER
);

CREATE TABLE IF NOT EXISTS printers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    paper_width INTEGER NOT NULL DEFAULT 80,
    company_id INTEGER NOT NULL,
    CONSTRAINT fk_printers_company_id FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_companies_default_printer_id'
    ) THEN
        ALTER TABLE companies 
        ADD CONSTRAINT fk_companies_default_printer_id 
        FOREIGN KEY (default_printer_id) REFERENCES printers (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255),
    cpf VARCHAR(14),
    pis VARCHAR(20),
    endereco VARCHAR(255),
    data_nascimento DATE,
    password_hash VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    role VARCHAR(50) NOT NULL DEFAULT 'EMPLOYEE' CHECK (role IN ('EMPLOYEE', 'MANAGER', 'MAINTAINER')),
    can_manual_punch_desktop BOOLEAN NOT NULL DEFAULT TRUE,
    can_manual_punch_mobile BOOLEAN NOT NULL DEFAULT FALSE,
    can_export_report BOOLEAN NOT NULL DEFAULT FALSE,
    is_exempt_from_rules BOOLEAN NOT NULL DEFAULT FALSE,
    is_tolerance_exempt BOOLEAN NOT NULL DEFAULT FALSE,
    auto_print_receipt BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS device_credentials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    key_type devicekeytype NOT NULL DEFAULT 'DEVICE',
    api_key_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS firmwares (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version VARCHAR(50) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS holidays (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_biometrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    sensor_index INTEGER,
    template_data TEXT,
    finger_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_biometrics_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_work_schedule_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    daily_hours DOUBLE PRECISION NOT NULL,
    entry_1 TIME WITHOUT TIME ZONE,
    exit_1 TIME WITHOUT TIME ZONE,
    entry_2 TIME WITHOUT TIME ZONE,
    exit_2 TIME WITHOUT TIME ZONE,
    valid_from DATE NOT NULL,
    valid_until DATE,
    is_daily_excess_enabled BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_user_work_schedule_configs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS time_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    record_type recordtype NOT NULL,
    record_datetime TIMESTAMPTZ NOT NULL,
    ip_address VARCHAR(45),
    device_name VARCHAR(255),
    platform VARCHAR(50),
    biometric_id INTEGER,
    edited_by INTEGER,
    edit_justification VARCHAR(300),
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER,
    is_ignored BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    original_record_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_time_records_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_time_records_biometric_id FOREIGN KEY (biometric_id) REFERENCES user_biometrics (id) ON DELETE SET NULL,
    CONSTRAINT fk_time_records_edited_by FOREIGN KEY (edited_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_time_records_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_time_records_original_record_id FOREIGN KEY (original_record_id) REFERENCES time_records (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS adjustment_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    adjustment_type adjustmenttype NOT NULL,
    record_type recordtype,
    target_date DATE NOT NULL,
    time TIME WITHOUT TIME ZONE,
    amount_hours DOUBLE PRECISION,
    reason_text TEXT,
    status adjustmentstatus NOT NULL DEFAULT 'PENDING',
    manager_id INTEGER,
    manager_comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER,
    approved_amount_hours DOUBLE PRECISION,
    CONSTRAINT fk_adjustment_requests_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_adjustment_requests_manager_id FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_adjustment_requests_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS adjustment_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_request_id INTEGER NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adjustment_attachments_request_id FOREIGN KEY (adjustment_request_id) REFERENCES adjustment_requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payroll_closures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    year INTEGER NOT NULL CHECK (year >= 2000),
    is_closed BOOLEAN NOT NULL DEFAULT TRUE,
    closed_by_user_id INTEGER NOT NULL,
    closed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    report_path VARCHAR(500),
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER,
    reopen_observation TEXT,
    CONSTRAINT fk_payroll_closures_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payroll_closures_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    action VARCHAR(100) NOT NULL,
    entity VARCHAR(100) NOT NULL,
    entity_id INTEGER,
    old_data JSONB,
    new_data JSONB,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS routine_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_type VARCHAR(100) NOT NULL,
    execution_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    target_date DATE,
    status VARCHAR(50) NOT NULL,
    details TEXT
);

CREATE TABLE IF NOT EXISTS alembic_version (
    version_num VARCHAR(32) NOT NULL PRIMARY KEY
);

INSERT INTO alembic_version (version_num)
VALUES ('045')
ON CONFLICT (version_num) DO NOTHING;

CREATE UNIQUE INDEX IF NOT EXISTS ix_companies_cnpj ON companies (cnpj);
CREATE INDEX IF NOT EXISTS ix_companies_id ON companies (id);
CREATE INDEX IF NOT EXISTS ix_companies_default_printer_id ON companies (default_printer_id);

CREATE INDEX IF NOT EXISTS ix_printers_id ON printers (id);
CREATE INDEX IF NOT EXISTS ix_printers_company_id ON printers (company_id);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_cpf ON users (cpf);
CREATE INDEX IF NOT EXISTS ix_users_id ON users (id);
CREATE INDEX IF NOT EXISTS idx_users_active_role ON users (is_active, role);
CREATE INDEX IF NOT EXISTS idx_users_name_trgm ON users USING gin (name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS ix_device_credentials_id ON device_credentials (id);
CREATE INDEX IF NOT EXISTS idx_device_credentials_lookup ON device_credentials (api_key_hash, key_type, is_active);

CREATE INDEX IF NOT EXISTS ix_firmwares_id ON firmwares (id);
CREATE INDEX IF NOT EXISTS idx_firmwares_version_created ON firmwares (version, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_holidays_id ON holidays (id);

CREATE INDEX IF NOT EXISTS ix_user_biometrics_id ON user_biometrics (id);
CREATE INDEX IF NOT EXISTS ix_user_biometrics_user_id ON user_biometrics (user_id);
CREATE INDEX IF NOT EXISTS idx_user_biometrics_sensor_lookup ON user_biometrics (sensor_index);

CREATE INDEX IF NOT EXISTS ix_user_work_schedule_configs_id ON user_work_schedule_configs (id);
CREATE INDEX IF NOT EXISTS ix_user_work_schedule_configs_user_id ON user_work_schedule_configs (user_id);
CREATE INDEX IF NOT EXISTS idx_user_work_schedules_active ON user_work_schedule_configs (user_id, valid_from, valid_until);

CREATE INDEX IF NOT EXISTS ix_time_records_id ON time_records (id);
CREATE INDEX IF NOT EXISTS idx_tr_user_date ON time_records (user_id, record_datetime);
CREATE INDEX IF NOT EXISTS idx_tr_ignored ON time_records (is_ignored);
CREATE INDEX IF NOT EXISTS idx_tr_active_period ON time_records (user_id, record_datetime) WHERE is_ignored = FALSE;
CREATE INDEX IF NOT EXISTS ix_time_records_biometric_id ON time_records (biometric_id);
CREATE INDEX IF NOT EXISTS ix_time_records_edited_by ON time_records (edited_by);
CREATE INDEX IF NOT EXISTS ix_time_records_deleted_by ON time_records (deleted_by);
CREATE INDEX IF NOT EXISTS ix_time_records_original_record_id ON time_records (original_record_id);

CREATE INDEX IF NOT EXISTS ix_adjustment_requests_id ON adjustment_requests (id);
CREATE INDEX IF NOT EXISTS idx_adj_user_date ON adjustment_requests (user_id, target_date);
CREATE INDEX IF NOT EXISTS idx_adj_status ON adjustment_requests (status);
CREATE INDEX IF NOT EXISTS ix_adjustment_requests_manager_id ON adjustment_requests (manager_id);
CREATE INDEX IF NOT EXISTS ix_adjustment_requests_deleted_by ON adjustment_requests (deleted_by);

CREATE INDEX IF NOT EXISTS ix_adjustment_attachments_id ON adjustment_attachments (id);
CREATE INDEX IF NOT EXISTS ix_adjustment_attachments_request_id ON adjustment_attachments (adjustment_request_id);

CREATE INDEX IF NOT EXISTS ix_payroll_closures_id ON payroll_closures (id);
CREATE INDEX IF NOT EXISTS idx_payroll_closures_period ON payroll_closures (year, month);
CREATE INDEX IF NOT EXISTS ix_payroll_closures_closed_by ON payroll_closures (closed_by_user_id);
CREATE INDEX IF NOT EXISTS ix_payroll_closures_deleted_by ON payroll_closures (deleted_by);

CREATE INDEX IF NOT EXISTS ix_audit_logs_id ON audit_logs (id);
CREATE INDEX IF NOT EXISTS idx_audit_user_action ON audit_logs (user_id, action);
CREATE INDEX IF NOT EXISTS idx_audit_entity_time ON audit_logs (entity, entity_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_new_data_gin ON audit_logs USING gin (new_data);
CREATE INDEX IF NOT EXISTS idx_audit_logs_old_data_gin ON audit_logs USING gin (old_data);

CREATE INDEX IF NOT EXISTS ix_routine_logs_id ON routine_logs (id);
CREATE INDEX IF NOT EXISTS ix_routine_logs_routine_type ON routine_logs (routine_type);
CREATE INDEX IF NOT EXISTS idx_routine_logs_execution_time ON routine_logs (execution_time DESC);

COMMENT ON TABLE companies IS 'Empresas e filiais';
COMMENT ON COLUMN companies.id IS 'ID da empresa';
COMMENT ON COLUMN companies.name IS 'Razao social ou nome';
COMMENT ON COLUMN companies.cnpj IS 'CNPJ da empresa';
COMMENT ON COLUMN companies.address IS 'Endereco da empresa';
COMMENT ON COLUMN companies.phone IS 'Telefone de contato';
COMMENT ON COLUMN companies.logo_path IS 'Caminho do logotipo';
COMMENT ON COLUMN companies.auto_print_receipt IS 'Impressao automatica de comprovante';
COMMENT ON COLUMN companies.default_printer_id IS 'ID da impressora padrao';

COMMENT ON TABLE printers IS 'Impressoras termicas';
COMMENT ON COLUMN printers.id IS 'ID da impressora';
COMMENT ON COLUMN printers.name IS 'Nome da impressora';
COMMENT ON COLUMN printers.address IS 'Endereco IP ou porta';
COMMENT ON COLUMN printers.status IS 'Status ativo/inativo';
COMMENT ON COLUMN printers.paper_width IS 'Largura do papel em mm';
COMMENT ON COLUMN printers.company_id IS 'ID da empresa vinculada';

COMMENT ON TABLE users IS 'Usuarios do sistema';
COMMENT ON COLUMN users.id IS 'ID do usuario';
COMMENT ON COLUMN users.username IS 'Login do usuario';
COMMENT ON COLUMN users.name IS 'Nome do usuario';
COMMENT ON COLUMN users.email IS 'E-mail do usuario';
COMMENT ON COLUMN users.cpf IS 'CPF do usuario';
COMMENT ON COLUMN users.pis IS 'PIS do usuario';
COMMENT ON COLUMN users.endereco IS 'Endereco do usuario';
COMMENT ON COLUMN users.data_nascimento IS 'Data de nascimento';
COMMENT ON COLUMN users.password_hash IS 'Hash da senha';
COMMENT ON COLUMN users.is_active IS 'Status ativo';
COMMENT ON COLUMN users.role IS 'Perfil de acesso';
COMMENT ON COLUMN users.can_manual_punch_desktop IS 'Permite batida manual desktop';
COMMENT ON COLUMN users.can_manual_punch_mobile IS 'Permite batida manual mobile';
COMMENT ON COLUMN users.can_export_report IS 'Permite exportar relatorios';
COMMENT ON COLUMN users.is_exempt_from_rules IS 'Isento de regras gerais';
COMMENT ON COLUMN users.is_tolerance_exempt IS 'Isento de tolerancia';
COMMENT ON COLUMN users.auto_print_receipt IS 'Impressao automatica de comprovante';
COMMENT ON COLUMN users.created_at IS 'Data de criacao';
COMMENT ON COLUMN users.updated_at IS 'Data de atualizacao';

COMMENT ON TABLE device_credentials IS 'Credenciais de dispositivos e APIs';
COMMENT ON COLUMN device_credentials.id IS 'ID da credencial';
COMMENT ON COLUMN device_credentials.name IS 'Nome da credencial';
COMMENT ON COLUMN device_credentials.key_type IS 'Tipo de chave';
COMMENT ON COLUMN device_credentials.api_key_hash IS 'Hash da chave de API';
COMMENT ON COLUMN device_credentials.is_active IS 'Status ativo';
COMMENT ON COLUMN device_credentials.created_at IS 'Data de criacao';
COMMENT ON COLUMN device_credentials.updated_at IS 'Data de atualizacao';

COMMENT ON TABLE firmwares IS 'Firmwares de dispositivos';
COMMENT ON COLUMN firmwares.id IS 'ID do firmware';
COMMENT ON COLUMN firmwares.version IS 'Versao do firmware';
COMMENT ON COLUMN firmwares.file_path IS 'Caminho do arquivo';
COMMENT ON COLUMN firmwares.created_at IS 'Data de criacao';

COMMENT ON TABLE holidays IS 'Feriados cadastrados';
COMMENT ON COLUMN holidays.id IS 'ID do feriado';
COMMENT ON COLUMN holidays.date IS 'Data do feriado';
COMMENT ON COLUMN holidays.name IS 'Nome do feriado';

COMMENT ON TABLE user_biometrics IS 'Biometrias dos usuarios';
COMMENT ON COLUMN user_biometrics.id IS 'ID da biometria';
COMMENT ON COLUMN user_biometrics.user_id IS 'ID do usuario';
COMMENT ON COLUMN user_biometrics.sensor_index IS 'Indice no sensor biometrico';
COMMENT ON COLUMN user_biometrics.template_data IS 'Template biometrico';
COMMENT ON COLUMN user_biometrics.finger_id IS 'Identificador do dedo';
COMMENT ON COLUMN user_biometrics.created_at IS 'Data de criacao';

COMMENT ON TABLE user_work_schedule_configs IS 'Configuracoes de jornada de trabalho';
COMMENT ON COLUMN user_work_schedule_configs.id IS 'ID da jornada';
COMMENT ON COLUMN user_work_schedule_configs.user_id IS 'ID do usuario';
COMMENT ON COLUMN user_work_schedule_configs.day_of_week IS 'Dia da semana (0-6)';
COMMENT ON COLUMN user_work_schedule_configs.daily_hours IS 'Horas diarias previstas';
COMMENT ON COLUMN user_work_schedule_configs.entry_1 IS 'Entrada 1';
COMMENT ON COLUMN user_work_schedule_configs.exit_1 IS 'Saida 1';
COMMENT ON COLUMN user_work_schedule_configs.entry_2 IS 'Entrada 2';
COMMENT ON COLUMN user_work_schedule_configs.exit_2 IS 'Saida 2';
COMMENT ON COLUMN user_work_schedule_configs.valid_from IS 'Inicio de vigencia';
COMMENT ON COLUMN user_work_schedule_configs.valid_until IS 'Fim de vigencia';
COMMENT ON COLUMN user_work_schedule_configs.is_daily_excess_enabled IS 'Compensacao de excesso diario';

COMMENT ON TABLE time_records IS 'Registros de ponto eletronico';
COMMENT ON COLUMN time_records.id IS 'ID do ponto';
COMMENT ON COLUMN time_records.user_id IS 'ID do usuario';
COMMENT ON COLUMN time_records.record_type IS 'Tipo de batida';
COMMENT ON COLUMN time_records.record_datetime IS 'Data e hora da batida';
COMMENT ON COLUMN time_records.ip_address IS 'IP de origem';
COMMENT ON COLUMN time_records.device_name IS 'Nome do dispositivo';
COMMENT ON COLUMN time_records.platform IS 'Plataforma de origem';
COMMENT ON COLUMN time_records.biometric_id IS 'ID da biometria utilizada';
COMMENT ON COLUMN time_records.edited_by IS 'ID do editor manual';
COMMENT ON COLUMN time_records.edit_justification IS 'Justificativa da edicao';
COMMENT ON COLUMN time_records.deleted_at IS 'Data de exclusao logica';
COMMENT ON COLUMN time_records.deleted_by IS 'ID de quem excluiu';
COMMENT ON COLUMN time_records.is_ignored IS 'Batida desconsiderada';
COMMENT ON COLUMN time_records.is_verified IS 'Batida verificada';
COMMENT ON COLUMN time_records.original_record_id IS 'ID do ponto original';
COMMENT ON COLUMN time_records.created_at IS 'Data de criacao';
COMMENT ON COLUMN time_records.updated_at IS 'Data de atualizacao';

COMMENT ON TABLE adjustment_requests IS 'Solicitacoes de ajuste de ponto';
COMMENT ON COLUMN adjustment_requests.id IS 'ID do ajuste';
COMMENT ON COLUMN adjustment_requests.user_id IS 'ID do solicitante';
COMMENT ON COLUMN adjustment_requests.adjustment_type IS 'Tipo de ajuste';
COMMENT ON COLUMN adjustment_requests.record_type IS 'Tipo de batida';
COMMENT ON COLUMN adjustment_requests.target_date IS 'Data do ajuste';
COMMENT ON COLUMN adjustment_requests.time IS 'Horario proposto';
COMMENT ON COLUMN adjustment_requests.amount_hours IS 'Horas solicitadas';
COMMENT ON COLUMN adjustment_requests.reason_text IS 'Motivo do ajuste';
COMMENT ON COLUMN adjustment_requests.status IS 'Status da solicitacao';
COMMENT ON COLUMN adjustment_requests.manager_id IS 'ID do gestor avaliador';
COMMENT ON COLUMN adjustment_requests.manager_comment IS 'Parecer do gestor';
COMMENT ON COLUMN adjustment_requests.created_at IS 'Data de criacao';
COMMENT ON COLUMN adjustment_requests.reviewed_at IS 'Data de avaliacao';
COMMENT ON COLUMN adjustment_requests.deleted_at IS 'Data de exclusao';
COMMENT ON COLUMN adjustment_requests.deleted_by IS 'ID de quem excluiu';
COMMENT ON COLUMN adjustment_requests.approved_amount_hours IS 'Horas aprovadas';

COMMENT ON TABLE adjustment_attachments IS 'Anexos de ajustes de ponto';
COMMENT ON COLUMN adjustment_attachments.id IS 'ID do anexo';
COMMENT ON COLUMN adjustment_attachments.adjustment_request_id IS 'ID do ajuste vinculado';
COMMENT ON COLUMN adjustment_attachments.file_path IS 'Caminho do arquivo';
COMMENT ON COLUMN adjustment_attachments.file_type IS 'Tipo do arquivo';
COMMENT ON COLUMN adjustment_attachments.uploaded_at IS 'Data de upload';

COMMENT ON TABLE payroll_closures IS 'Fechamentos de folha de ponto';
COMMENT ON COLUMN payroll_closures.id IS 'ID do fechamento';
COMMENT ON COLUMN payroll_closures.month IS 'Mes de competencia';
COMMENT ON COLUMN payroll_closures.year IS 'Ano de competencia';
COMMENT ON COLUMN payroll_closures.is_closed IS 'Status de fechamento';
COMMENT ON COLUMN payroll_closures.closed_by_user_id IS 'ID de quem fechou';
COMMENT ON COLUMN payroll_closures.closed_at IS 'Data de fechamento';
COMMENT ON COLUMN payroll_closures.report_path IS 'Caminho do relatorio';
COMMENT ON COLUMN payroll_closures.deleted_at IS 'Data de reabertura';
COMMENT ON COLUMN payroll_closures.deleted_by IS 'ID de quem reabriu';
COMMENT ON COLUMN payroll_closures.reopen_observation IS 'Motivo da reabertura';

COMMENT ON TABLE audit_logs IS 'Logs de auditoria';
COMMENT ON COLUMN audit_logs.id IS 'ID do log';
COMMENT ON COLUMN audit_logs.user_id IS 'ID do usuario';
COMMENT ON COLUMN audit_logs.action IS 'Acao executada';
COMMENT ON COLUMN audit_logs.entity IS 'Entidade afetada';
COMMENT ON COLUMN audit_logs.entity_id IS 'ID do registro afetado';
COMMENT ON COLUMN audit_logs.old_data IS 'Dados anteriores (JSONB)';
COMMENT ON COLUMN audit_logs.new_data IS 'Dados novos (JSONB)';
COMMENT ON COLUMN audit_logs.timestamp IS 'Data e hora do evento';

COMMENT ON TABLE routine_logs IS 'Logs de rotinas automaticas';
COMMENT ON COLUMN routine_logs.id IS 'ID do log';
COMMENT ON COLUMN routine_logs.routine_type IS 'Tipo da rotina';
COMMENT ON COLUMN routine_logs.execution_time IS 'Data e hora de execucao';
COMMENT ON COLUMN routine_logs.target_date IS 'Data alvo da rotina';
COMMENT ON COLUMN routine_logs.status IS 'Status da execucao';
COMMENT ON COLUMN routine_logs.details IS 'Detalhes da execucao';

COMMENT ON TABLE alembic_version IS 'Versao do schema no Alembic';
COMMENT ON COLUMN alembic_version.version_num IS 'Identificador da revisao';

COMMIT;
"""


def load_environment() -> None:
    env_path = ROOT_DIR / ".env"
    if env_path.exists() and load_dotenv:
        load_dotenv(dotenv_path=env_path, override=True)


def get_pg_credentials() -> dict[str, str]:
    load_environment()
    db = os.getenv("POSTGRES_DB", "spe_db")
    user = os.getenv("POSTGRES_USER", "spe")
    password = os.getenv("POSTGRES_PASSWORD", "")
    host = os.getenv("POSTGRES_HOST", "localhost")
    port = os.getenv("POSTGRES_PORT", "5432")

    uri = os.getenv("SQLALCHEMY_DATABASE_URI", "")
    if uri and "postgresql" in uri:
        clean_uri = uri.replace("postgresql+asyncpg://", "").replace("postgresql://", "")
        if "@" in clean_uri:
            auth, host_part = clean_uri.split("@", 1)
            if ":" in auth:
                user, password = auth.split(":", 1)
            if "/" in host_part:
                hp, db_part = host_part.split("/", 1)
                db = db_part.split("?")[0]
                if ":" in hp:
                    host, port = hp.split(":", 1)
                else:
                    host = hp

    return {
        "dbname": db,
        "user": user,
        "password": password,
        "host": host,
        "port": port,
    }


def format_cell(table_name: str, col_name: str, val: object) -> str:
    if val is None:
        return "NULL"

    if col_name in BOOLEAN_COLUMNS.get(table_name, set()):
        val_str = str(val).strip().lower()
        if val_str in ("1", "true", "t"):
            return "TRUE"
        if val_str in ("0", "false", "f"):
            return "FALSE"
        return "NULL"

    if col_name in JSONB_COLUMNS.get(table_name, set()):
        if isinstance(val, dict):
            val_str = json.dumps(val, ensure_ascii=False)
        else:
            val_str = str(val)
        escaped = val_str.replace("'", "''")
        return f"'{escaped}'::jsonb"

    if isinstance(val, (int, float)):
        return str(val)

    val_str = str(val)
    if "\n" in val_str or "\r" in val_str:
        escaped = (
            val_str.replace("\\", "\\\\")
            .replace("'", "''")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        )
        return f"E'{escaped}'"

    val_str = val_str.replace("'", "''")
    return f"'{val_str}'"


def export_ddl(output_path: Path = DEFAULT_DDL_PATH) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(DDL_SQL_CONTENT.strip() + "\n")
    print(f"[OK] DDL exportado com sucesso em: {output_path}")


def export_data(
        sqlite_path: Path = DEFAULT_SQLITE_PATH,
        output_path: Path = DEFAULT_DML_PATH,
        batch_size: int = 100,
) -> dict[str, int]:
    if not sqlite_path.exists():
        raise FileNotFoundError(f"Arquivo SQLite não encontrado: {sqlite_path}")

    conn = sqlite3.connect(sqlite_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    stats: dict[str, int] = {}
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as out:
        out.write("BEGIN;\n\n")
        out.write("SET client_encoding = 'UTF8';\n")
        out.write("SET standard_conforming_strings = on;\n")
        out.write("SET check_function_bodies = false;\n")
        out.write("SET client_min_messages = warning;\n")
        out.write("SET timezone = 'America/Fortaleza';\n\n")

        for table_name in TABLE_ORDER:
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
                (table_name,),
            )
            if not cursor.fetchone():
                stats[table_name] = 0
                continue

            order_clause = " ORDER BY id ASC" if table_name != "alembic_version" else ""
            cursor.execute(f"SELECT * FROM {table_name}{order_clause}")
            rows = cursor.fetchall()
            stats[table_name] = len(rows)

            if not rows:
                continue

            cols = list(rows[0].keys())
            cols_str = ", ".join(f'"{c}"' for c in cols)

            if table_name == "alembic_version":
                for r in rows:
                    v = format_cell(table_name, "version_num", r["version_num"])
                    out.write(
                        f"INSERT INTO alembic_version (version_num) VALUES ({v}) ON CONFLICT (version_num) DO NOTHING;\n"
                    )
                out.write("\n")
                continue

            for i in range(0, len(rows), batch_size):
                batch = rows[i: i + batch_size]
                value_tuples = []
                for row in batch:
                    formatted_vals = [
                        format_cell(table_name, c, row[c]) for c in cols
                    ]
                    value_tuples.append("(" + ", ".join(formatted_vals) + ")")

                values_str = ",\n  ".join(value_tuples)
                out.write(
                    f"INSERT INTO {table_name} ({cols_str}) VALUES\n  {values_str};\n"
                )
            out.write("\n")

        for table_name in IDENTITY_TABLES:
            out.write(
                f"SELECT setval(pg_get_serial_sequence('{table_name}', 'id'), COALESCE((SELECT MAX(id) FROM {table_name}), 1));\n"
            )

        out.write("\nCOMMIT;\n")

    conn.close()
    print(f"[OK] Dados exportados com sucesso em: {output_path}")
    print("\nResumo de registros exportados:")
    total = 0
    for table, count in stats.items():
        print(f"  - {table:30}: {count:>6} registros")
        total += count
    print(f"  Total: {total} registros")
    return stats


def connect_with_retry(creds: dict[str, str], max_retries: int = 30, delay: float = 1.0):
    for attempt in range(1, max_retries + 1):
        try:
            return psycopg2.connect(**creds)
        except (psycopg2.OperationalError, psycopg2.DatabaseError) as e:
            if attempt == max_retries:
                raise RuntimeError(f"Tempo limite aguardando o PostgreSQL: {e}") from e
            if attempt == 1 or attempt % 5 == 0:
                print(f"Aguardando o PostgreSQL ficar pronto... (tentativa {attempt}/{max_retries})")
            time.sleep(delay)


def populate_postgresql(
        dml_path: Path = DEFAULT_DML_PATH,
        truncate_first: bool = True,
) -> None:
    if psycopg2 is None:
        raise RuntimeError("Driver psycopg2 não está instalado no ambiente virtual.")

    if not dml_path.exists():
        print(f"Arquivo de dados {dml_path.name} não encontrado. Gerando a partir do SQLite...")
        export_data(output_path=dml_path)

    creds = get_pg_credentials()
    print(
        f"Conectando ao PostgreSQL em {creds['host']}:{creds['port']}/{creds['dbname']} (usuário: {creds['user']})...")

    conn = connect_with_retry(creds)
    conn.autocommit = False
    cursor = conn.cursor()

    try:
        if truncate_first:
            print("Limpando tabelas existentes antes da inserção...")
            truncate_tables = [t for t in TABLE_ORDER if t != "alembic_version"]
            truncate_query = f"TRUNCATE TABLE {', '.join(truncate_tables)} RESTART IDENTITY CASCADE;"
            cursor.execute(truncate_query)
            conn.commit()
            print("[OK] Tabelas truncadas com sucesso.")

        print(f"Executando script de inserção: {dml_path}...")
        sql_content = dml_path.read_text(encoding="utf-8")
        cursor.execute(sql_content)
        conn.commit()
        print("[OK] Carga de dados realizada e transação confirmada com sucesso!")

    except Exception as e:
        conn.rollback()
        raise RuntimeError(f"Falha ao popular o banco PostgreSQL: {e}") from e
    finally:
        cursor.close()
        conn.close()


def verify_sync(sqlite_path: Path = DEFAULT_SQLITE_PATH) -> bool:
    if psycopg2 is None:
        raise RuntimeError("Driver psycopg2 não está instalado.")

    if not sqlite_path.exists():
        raise FileNotFoundError(f"Arquivo SQLite não encontrado: {sqlite_path}")

    creds = get_pg_credentials()
    pg_conn = connect_with_retry(creds)
    pg_cur = pg_conn.cursor()

    sq_conn = sqlite3.connect(sqlite_path)
    sq_cur = sq_conn.cursor()

    all_matched = True
    print("\n" + "=" * 65)
    print(f"{'TABELA':30} | {'SQLITE':>10} | {'POSTGRES':>10} | {'STATUS':^7}")
    print("=" * 65)

    for table in TABLE_ORDER:
        sq_cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
            (table,),
        )
        if not sq_cur.fetchone():
            sq_count = 0
        else:
            sq_cur.execute(f"SELECT COUNT(*) FROM {table}")
            sq_count = sq_cur.fetchone()[0]

        try:
            pg_cur.execute(f"SELECT COUNT(*) FROM {table}")
            pg_count = pg_cur.fetchone()[0]
        except Exception:
            pg_conn.rollback()
            pg_count = -1

        match = (sq_count == pg_count)
        if not match:
            all_matched = False

        status_str = "OK" if match else "DIFF"
        print(f"{table:30} | {sq_count:>10} | {pg_count:>10} | {status_str:^7}")

    print("=" * 65)
    pg_cur.close()
    pg_conn.close()
    sq_conn.close()

    if all_matched:
        print("[SUCESSO] 100% de paridade entre SQLite e PostgreSQL!")
    else:
        print("[ALERTA] Diferenças detectadas entre as bases de dados.")
    return all_matched


def find_pg_binary(name: str) -> str | None:
    bin_path = shutil.which(name)
    if bin_path:
        return bin_path
    import glob
    for pattern in [
        rf"C:\Program Files\PostgreSQL\*\bin\{name}.exe",
        rf"C:\Program Files (x86)\PostgreSQL\*\bin\{name}.exe",
    ]:
        matches = glob.glob(pattern)
        if matches:
            matches.sort(reverse=True)
            return matches[0]
    return None


def dump_database(output_path: Path = DEFAULT_DUMP_PATH) -> None:
    creds = get_pg_credentials()
    pg_dump = find_pg_binary("pg_dump")
    print(f"Gerando dump fidedigno oficial do PostgreSQL em: {output_path}...")

    if pg_dump:
        print(f"Utilizando ferramenta nativa do PostgreSQL: {pg_dump}")
        env = os.environ.copy()
        if creds.get("password"):
            env["PGPASSWORD"] = str(creds["password"])
        cmd = [
            pg_dump,
            "-h", str(creds.get("host", "localhost")),
            "-p", str(creds.get("port", 5432)),
            "-U", str(creds.get("user", "spe")),
            "-d", str(creds.get("dbname", "spe_db")),
            "--clean",
            "--if-exists",
            "--no-owner",
            "--no-privileges",
            "--encoding=UTF8",
            "-f", str(output_path),
        ]
        res = subprocess.run(cmd, env=env, capture_output=True, text=True)
        if res.returncode == 0 and output_path.exists() and output_path.stat().st_size > 0:
            print(f"[OK] Dump oficial PostgreSQL gerado com sucesso! Tamanho: {output_path.stat().st_size:,} bytes")
            return
        print(f"[AVISO] pg_dump local falhou ({res.stderr.strip()}). Tentando via Docker...")

    if shutil.which("docker"):
        print("Executando pg_dump via container Docker spe_postgres...")
        cmd = [
            "docker", "exec",
            "-e", f"PGPASSWORD={creds.get('password', '')}",
            "spe_postgres",
            "pg_dump",
            "-U", str(creds.get("user", "spe")),
            "-d", str(creds.get("dbname", "spe_db")),
            "--clean",
            "--if-exists",
            "--no-owner",
            "--no-privileges",
            "--encoding=UTF8",
        ]
        res = subprocess.run(cmd, capture_output=True)
        if res.returncode == 0 and res.stdout:
            with open(output_path, "wb") as f:
                f.write(res.stdout)
            print(f"[OK] Dump via Docker gerado com sucesso! Tamanho: {output_path.stat().st_size:,} bytes")
            return
        print("[AVISO] pg_dump via Docker falhou. Tentando fallback Python...")

    from app.features.system.backup_service import backup_service
    params = backup_service._get_postgres_connection_params()
    success = backup_service._dump_postgresql_python(str(output_path), params)
    if success and output_path.exists() and output_path.stat().st_size > 0:
        print(f"[OK] Dump gerado com sucesso via Python dumper! Tamanho: {output_path.stat().st_size:,} bytes")
    else:
        raise RuntimeError("Não foi possível gerar o dump do PostgreSQL.")


def restore_database(input_path: Path = DEFAULT_DUMP_PATH) -> None:
    if not input_path.exists():
        raise FileNotFoundError(f"Arquivo de dump {input_path} não encontrado!")

    creds = get_pg_credentials()
    psql = find_pg_binary("psql")
    print(f"Restaurando banco PostgreSQL a partir de: {input_path}...")

    if psql:
        print(f"Utilizando utilitário nativo psql: {psql}")
        env = os.environ.copy()
        if creds.get("password"):
            env["PGPASSWORD"] = str(creds["password"])
        cmd = [
            psql,
            "-h", str(creds.get("host", "localhost")),
            "-p", str(creds.get("port", 5432)),
            "-U", str(creds.get("user", "spe")),
            "-d", str(creds.get("dbname", "spe_db")),
            "-f", str(input_path),
        ]
        res = subprocess.run(cmd, env=env, capture_output=True, text=True)
        if res.returncode == 0:
            print("[OK] Banco PostgreSQL restaurado com sucesso via psql!")
            return
        print(f"[AVISO] psql local falhou ({res.stderr.strip()}). Tentando via Docker...")

    if shutil.which("docker"):
        print("Restaurando via Docker spe_postgres psql...")
        with open(input_path, "rb") as f:
            data = f.read()
        cmd = [
            "docker", "exec", "-i",
            "-e", f"PGPASSWORD={creds.get('password', '')}",
            "spe_postgres",
            "psql",
            "-U", str(creds.get("user", "spe")),
            "-d", str(creds.get("dbname", "spe_db")),
        ]
        res = subprocess.run(cmd, input=data, capture_output=True)
        if res.returncode == 0:
            print("[OK] Banco PostgreSQL restaurado com sucesso via Docker psql!")
            return
        print(f"[AVISO] Restauração via Docker falhou: {res.stderr.decode('utf-8', errors='ignore')}")

    conn = connect_with_retry(creds)
    try:
        with conn.cursor() as cur, open(input_path, "r", encoding="utf-8", errors="ignore") as f:
            sql = f.read()
            cur.execute(sql)
            conn.commit()
        print("[OK] Banco restaurado com sucesso via psycopg2!")
    finally:
        conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Utilitário de migração, geração de SQL e população de dados entre SQLite e PostgreSQL."
    )
    parser.add_argument(
        "--dump",
        action="store_true",
        help="Gera um dump oficial e fidedigno do PostgreSQL (padrão: spe_dump.sql)",
    )
    parser.add_argument(
        "--restore",
        action="store_true",
        help="Restaura o PostgreSQL a partir de um arquivo de dump (padrão: spe_dump.sql)",
    )
    parser.add_argument(
        "--dump-file",
        type=Path,
        default=DEFAULT_DUMP_PATH,
        help="Caminho do arquivo de dump para --dump ou --restore (padrão: spe_dump.sql)",
    )
    parser.add_argument(
        "--export-ddl",
        action="store_true",
        help="Gera o script DDL em scripts/spe-db.sql",
    )
    parser.add_argument(
        "--export-data",
        action="store_true",
        help="Extrai os dados do SQLite e gera scripts/data_inserts_postgresql.sql",
    )
    parser.add_argument(
        "--export-all",
        action="store_true",
        help="Gera tanto o DDL quanto os inserts SQL",
    )
    parser.add_argument(
        "--populate",
        action="store_true",
        help="Executa a inserção dos dados no PostgreSQL via credenciais do .env",
    )
    parser.add_argument(
        "--no-truncate",
        action="store_true",
        help="Não limpa as tabelas antes de popular o PostgreSQL",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Compara a contagem de registros entre SQLite e PostgreSQL",
    )
    parser.add_argument(
        "--sqlite-db",
        type=Path,
        default=DEFAULT_SQLITE_PATH,
        help="Caminho do arquivo SQLite (padrão: spe.db)",
    )
    parser.add_argument(
        "--ddl-out",
        type=Path,
        default=DEFAULT_DDL_PATH,
        help="Caminho de saída da DDL",
    )
    parser.add_argument(
        "--dml-out",
        type=Path,
        default=DEFAULT_DML_PATH,
        help="Caminho de saída do script de dados",
    )

    args = parser.parse_args()

    if not any(
            [args.dump, args.restore, args.export_ddl, args.export_data, args.export_all, args.populate, args.verify]):
        parser.print_help()
        sys.exit(0)

    try:
        if args.dump:
            dump_database(args.dump_file)

        if args.restore:
            restore_database(args.dump_file)

        if args.export_all:
            export_ddl(args.ddl_out)
            export_data(args.sqlite_db, args.dml_out)
        else:
            if args.export_ddl:
                export_ddl(args.ddl_out)
            if args.export_data:
                export_data(args.sqlite_db, args.dml_out)

        if args.populate:
            populate_postgresql(args.dml_out, truncate_first=not args.no_truncate)

        if args.verify:
            verify_sync(args.sqlite_db)

    except Exception as e:
        print(f"\n[ERRO]: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
